- name: Ensure libvirt-bin is running
  sudo: yes
  service: name=libvirt-bin state=started enabled=yes
- name: Collect list of VMs
  sudo: yes
  virt: command=list_vms
  register: virtual_machines
- name: Issue graceful shutdowns
  sudo: yes
  virt: state=shutdown name={{item}}
  with_items: virtual_machines.list_vms
