# Copyright (c) 2014 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- hosts: all
  tasks:
    - include: disable_os_collect_config.yml
- hosts: undercloud
  name: Disable Undercloud
  sudo: yes
  tasks:
    - service: name={{ item }} enabled=no state=stopped
      with_items: helion_undercloud_services
- hosts: nova-compute
  name: Disable Overcloud Compute
  sudo: yes
  tasks:
    - service: name={{ item }} enabled=no state=stopped
      with_items: overcloud_compute_services
- hosts: swift-storage
  name: swift-storage
  sudo: yes
  tasks:
    - service: name={{ item }} enabled=no state=stopped
      with_items: overcloud_swift_services
- hosts: controller
  name: Disable Overcloud Controller
  sudo: yes
  tasks:
    - service: name={{ item }} enabled=no state=stopped
      with_items: overcloud_controller_services
- hosts: controllermgmt
  name: Disable Overcloud Controller Mgmt node
  sudo: yes
  tasks:
    - service: name={{ item }} enabled=no state=stopped
      with_items: overcloudmgmt_controller_services
- hosts: undercloud
  name: Rebuild and Refresh Undercloud
  tasks:
    - include: preserve_ssh_host_keys.yml
    - include: cleanup_cinder_volumes.yml
    - { include: rebuild.yml, instance_id: "{{ instance_id }}", rebuild_image_id: "{{ undercloud_rebuild_image_id }}" }
    - local_action: wait_for port=22 timeout=600 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=10
    - include: refresh_config.yml
- hosts: undercloud
  name: Enable Undercloud
  sudo: yes
  tasks:
    - include: disable_os_collect_config.yml
    - service: name={{ item }} enabled=yes state=started
      with_items: undercloud_services
- hosts: controller
  name: Rebuild and Refresh Controller
  tasks:
    - include: preserve_ssh_host_keys.yml
    - include: cleanup_cinder_volumes.yml
    - { include: rebuild.yml, instance_id: "{{ instance_id }}", rebuild_image_id: "{{ controller_rebuild_image_id }}" }
    - local_action: wait_for port=22 timeout=600 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=10
- hosts: controllermgmt
  name: Rebuild and Refresh ControllerMgmt
  tasks:
    - include: preserve_ssh_host_keys.yml
    - include: cleanup_cinder_volumes.yml
    - { include: rebuild.yml, instance_id: "{{ instance_id }}", rebuild_image_id: "{{ controllermgmt_rebuild_image_id }}" }
    - local_action: wait_for port=22 timeout=600 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=10
- hosts: controller:controllermgmt
  name: Re-Refresh Controller
  tasks:
    - include: refresh_config.yml
    - name: Disable os-collect-config on control nodes.
      include: disable_os_collect_config.yml
    - name: "Work around apache2 starting up at boot w/o config..."
      sudo: yes
      service: name=apache2 enabled=no state=stopped
    - name: "Run os-collect-config"
      sudo: yes
      command: os-collect-config --force --one
    - name: Re-run os-collect-config in case first one failed due to a race condition
      sudo: yes
      command: os-collect-config --noforce --one
- hosts: controllermgmt
  name: Enable Overcloud ControllerMgmt
  sudo: yes
  tasks:
    - name: Enable services
      service: name={{ item }} enabled=yes state=started
      with_items: overcloudmgmt_controller_service
- hosts: controller
  name: Enable Overcloud Controller
  sudo: yes
  tasks:
    - name: Enable services
      service: name={{ item }} enabled=yes state=started
      with_items: overcloud_controller_services
- hosts: swift-storage
  name: Rebuild and Refresh swift-storage
  tasks:
    - include: preserve_ssh_host_keys.yml
    - { include: rebuild.yml, instance_id: "{{ instance_id }}", rebuild_image_id: "{{ swift_storage_rebuild_image_id }}" }
    - local_action: wait_for port=22 timeout=600 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=10
    - include: refresh_config.yml
- hosts: swift-storage
  name: Enable Swift Storage
  sudo: yes
  tasks:
    - include: disable_os_collect_config.yml
    - name: "Run os-collect-config"
      sudo: yes
      command: os-collect-config --force --one
    - service: name={{ item }} enabled=yes state=started
      with_items: overcloud_swift_services
- hosts: nova-compute
  name: Rebuild and Refresh Nova Compute
  tasks:
    - include: preserve_ssh_host_keys.yml
    - { include: rebuild.yml, instance_id: "{{ instance_id }}", rebuild_image_id: "{{ nova_compute_rebuild_image_id }}" }
    - local_action: wait_for port=22 timeout=600 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=10
    - include: refresh_config.yml
- hosts: nova-compute
  name: Enable Overcloud Compute
  sudo: yes
  tasks:
    - include: disable_os_collect_config.yml
    - name: "Run os-collect-config"
      sudo: yes
      command: os-collect-config --force --one
    - service: name={{ item }} enabled=yes state=started
      with_items: overcloud_compute_services
